permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 徐顺
  email: xushun007@gmail.com
  link: http://www.cocoloud.net
  weibo: http://weibo.com/mircoheart
  github: https://github.com/microheart

# 站点信息
title: 徐顺的博客 
description: 徐顺的博客
url: http://www.cocoloud.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置
#ga:
#  id: UA-43667383-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: xandy-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Memcached
  - Redis
  - Hadoop

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
